run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter
    - unused        # Check for unused code
    - gofmt         # Check formatting
    - goimports     # Check imports
    - misspell      # Check for misspelled words
    - revive        # Fast, configurable, extensible linter
    - gosec         # Security issues
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Unused function parameters
    - bodyclose     # Check HTTP response body is closed
    - errname       # Check error naming conventions
    - errorlint     # Error wrapping issues
    - copyloopvar   # Check for loop variable capture (replaces exportloopref)
    - goconst       # Repeated strings that could be constants
    # - godot       # Check comments end in period (disabled for now)
    - nilerr        # Check nil error returns
    - nilnil        # Check returning nil, nil
    - noctx         # HTTP requests without context
    - prealloc      # Slice preallocation
    - predeclared   # Shadowing predeclared identifiers
    - usetesting    # Use t.Setenv instead of os.Setenv in tests (replaces tenv)
    - thelper       # Test helper detection
    - wastedassign  # Wasted assignments

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
    disable:
      - shadow        # Too strict for this project
      - fieldalignment # Struct field alignment - not critical for this project
  
  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"
  
  gosec:
    excludes:
      - G402  # TLS InsecureSkipVerify - needed for self-signed certs
      - G404  # Weak random number generator - not security critical
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  goimports:
    local-prefixes: github.com/mosleyit/reolink_api_wrapper

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - goconst
    
    # Exclude known issues in generated code
    - path: models\.go
      linters:
        - revive
        - stylecheck
  
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

